title: João Thiago Rodrigues de Sousa, PhD
url: "http://joaothiagors.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

#ID para rastreamento (Google Analytics, por exemplo)
tracking_id: #

footer: yes
footer_url: "https://github.com/joaothiagors"
footer_text: "Adaptado de Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Sobre"
   link: "/about/"
 - name: "Publicações"
   link: "/publication/"
 - name: "Disciplinas"
   link: "/courses/"
 - name: "Cursos"
   link: "/conferences/"
 - name: "Projetos"
   link: "/projects/"
 - name: "Orientações"
   link: "/advices/"
 - name: "Contato"
   link: "/contact/"
   
